version: '3.8'

services:
  node:
    container_name: ${COMPOSE_PROJECT_NAME}_node
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    command: sleep infinity
    env_file:
      - .env
    volumes:
      - .:/workspace:cached
      - ${SSH_SECRET_KEY_PATH}:/home/node/.ssh/id_rsa:cached
      - ${SSH_PUBLIC_KEY_PATH}:/home/node/.ssh/id_rsa.pub:cached
    networks:
      - app
    user: "node"
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    command: sleep infinity
    env_file:
      - .env
    volumes:
      - .:/workspace:cached
      - ${SSH_SECRET_KEY_PATH}:/home/developer/.ssh/id_rsa:cached
      - ${SSH_PUBLIC_KEY_PATH}:/home/developer/.ssh/id_rsa.pub:cached
    networks:
      - app
  dind:
    container_name: ${COMPOSE_PROJECT_NAME}_dind
    build:
      context: .
      dockerfile: docker/dind.Dockerfile
    command: sleep infinity
    privileged: true
    env_file:
      - .env
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SSH_SECRET_KEY_PATH}:/home/developer/.ssh/id_rsa:cached
      - ${SSH_PUBLIC_KEY_PATH}:/home/developer/.ssh/id_rsa.pub:cached
    networks:
      - app
networks:
  app:
    driver: bridge
